# Generated by Django 4.0.8 on 2023-01-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='volume',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
