# Generated by Django 4.0.8 on 2023-01-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_tracker', '0002_alter_pricehistory_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='total_btc',
            field=models.PositiveIntegerField(default=12054375),
            preserve_default=False,
        ),
    ]
