# Generated by Django 4.0.8 on 2023-01-11 09:39

from django.db import migrations, models
from datetime import date


def load_data(apps, schema_editor):
    PriceHistory = apps.get_model("bitcoin_tracker", "PriceHistory")

    PriceHistory(
        date=date(2013, 11, 29),
        price=1234.00,
        volume=3545,
        total_btc=12054375,
    ).save()
    PriceHistory(
        date=date(2012, 11, 29),
        price=12.15,
        volume=1879,
        total_btc=10504650,
    ).save()


class Migration(migrations.Migration):

    dependencies = [
        ("bitcoin_tracker", "0003_pricehistory_total_btc"),
    ]

    operations = [migrations.RunPython(load_data)]
