# Generated by Django 4.0.8 on 2023-01-19 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
